// CMS-SERVICES-01: Statischer Fallback für /services/produkt
export const FALLBACK_PRODUKT_BODY = [
  {
    _uid: 'fp-hero',
    component: 'service_hero',
    sequence_label: '03 / Produkt',
    headline: 'Ein Produkt beginnt nicht mit dem Release. Es beginnt damit, dass jemand seinen Alltag anders macht.',
    intro: 'Die Richtung ist klar. Die Präsentation überzeugt. Vielleicht gibt es bereits erste Screens oder Anforderungen. Tragfähig wird ein Produkt aber erst, wenn Menschen es verstehen, Systeme es mittragen und die nächste Entwicklung nicht wieder bei null anfängt.',
    meta: 'Ein gemeinsames Produktvorhaben · Umfang abhängig von Ausgangslage und Produktmoment',
    cta_label: 'Den Produktmoment besprechen →',
    cta_url: '/contact',
    hero_variant: 'foundation',
    h1_wide: true,
  },
  {
    _uid: 'fp-scene',
    component: 'service_scene',
    eyebrow: 'Der Moment davor',
    headline: 'Der erste echte Alltag beginnt nach dem Go-live.',
    text_1: 'Ein Produkt kann im Konzept überzeugend aussehen und trotzdem im Alltag scheitern. Menschen finden ihren Weg nicht. Inhalte fehlen. Ein Prozess läuft ausserhalb des Systems weiter. Eine Schnittstelle wird erst jetzt relevant. Oder die erste sinnvolle Weiterentwicklung ist nicht vorgesehen.',
    text_2: 'Produkt bedeutet deshalb nicht nur bauen. Es bedeutet, Erlebnis, Produktlogik, Systeme und Weiterentwicklung von Anfang an zusammenzubringen.',
  },
  {
    _uid: 'fp-artifact',
    component: 'service_artifact',
    eyebrow: 'Was daraus entsteht',
    headline: 'Ein Fundament, auf dem Alltag stattfinden kann.',
    lead: 'Das Produktfundament ist keine technische Architekturzeichnung und kein Wireframe. Es zeigt die vier Ebenen, die zusammenpassen müssen, damit ein Produkt nicht nur startet, sondern weiterträgt.',
    artifact_type: 'foundation',
    items: [
      { _uid: 'fp-art-1', component: 'service_artifact_item', item_id: '01', title: 'Was Menschen erleben', text: 'Wie Nutzer verstehen, handeln, Vertrauen aufbauen und wiederkommen.' },
      { _uid: 'fp-art-2', component: 'service_artifact_item', item_id: '02', title: 'Was das Produkt verspricht', text: 'Welche Regeln, Inhalte, Entscheidungen und Service-Momente das Produkt tragen.' },
      { _uid: 'fp-art-3', component: 'service_artifact_item', item_id: '03', title: 'Woran es anschliesst', text: 'Wie Daten, Plattformen, Teams und bestehende Abläufe sinnvoll zusammenspielen.' },
      { _uid: 'fp-art-4', component: 'service_artifact_item', item_id: '04', title: 'Wie es weiterwächst', text: 'Welche nächsten Schritte vorbereitet sind – und was bewusst erst später folgt.' },
    ],
    note: 'Das Produktfundament ist eine Arbeitsform von kenalu. Es ist kein Kundenprojekt.',
  },
  {
    _uid: 'fp-outcome',
    component: 'service_outcome',
    eyebrow: 'Danach',
    headline: 'Nicht nur ein Release. Eine tragfähige nächste Grundlage.',
    variant: '',
    items: [
      { _uid: 'fp-out-1', component: 'service_outcome_item', title: 'Der erste Umfang wird klarer.', text: 'Nicht alles, was möglich wäre, muss zum Start entstehen. Aber das, was entsteht, hat einen klaren Zweck.' },
      { _uid: 'fp-out-2', component: 'service_outcome_item', title: 'Entscheidungen bleiben verbunden.', text: 'Experience, Inhalte, Systeme und Engineering werden nicht nacheinander abgearbeitet, sondern in einer gemeinsamen Produktlogik geführt.' },
      { _uid: 'fp-out-3', component: 'service_outcome_item', title: 'Weiterentwicklung wird vorbereitet.', text: 'Nach dem ersten Release beginnt nicht wieder eine Grundsatzdiskussion. Es ist klarer, was vertieft, ergänzt oder bewusst nicht gebaut werden sollte.' },
    ],
  },
  {
    _uid: 'fp-kai',
    component: 'kai_dialogue',
    eyebrow: 'Den Alltag mitdenken',
    headline: 'Was soll für eure Nutzer oder Teams künftig spürbar einfacher werden?',
    intro: 'Beschreibt Kai kurz, wo ihr mit eurem Produkt steht. Er hilft euch, die nächste entscheidende Produktfrage einzuordnen.',
    context_key: 'produkt-story',
    initial_message: 'Hallo, ich bin Kai. Erzählt mir kurz, was bereits steht und was für Menschen im Alltag künftig besser funktionieren soll.',
    input_placeholder: 'Was soll für eure Nutzer oder Teams konkret einfacher werden?',
    suggested_prompts: [
      'Wir haben eine klare Idee, brauchen aber ein tragfähiges Produktkonzept.',
      'Unser Produkt funktioniert grundsätzlich, aber Nutzer und Systeme wachsen auseinander.',
      'Wir müssen Experience, Technologie und Weiterentwicklung besser zusammenbringen.',
    ],
    privacy_notice: 'Bitte keine vertraulichen Projekt-, Kunden- oder Personendaten eingeben. Kai ist ein KI-Assistent von kenalu.',
    show_contact_cta: true,
  },
  {
    _uid: 'fp-honest',
    component: 'service_honest_fit',
    eyebrow: 'Ehrliche Einordnung',
    headline: 'Produkt ist nicht immer der richtige erste Schritt.',
    list_items: [
      { _uid: 'fp-li-1', component: 'service_list_item', text: 'Ihr wisst noch nicht, welches Problem ihr wirklich lösen wollt oder wo der Nutzen liegt.' },
      { _uid: 'fp-li-2', component: 'service_list_item', text: 'Ihr wollt zuerst nur eine einzelne Hypothese prüfen, bevor ein grösseres Vorhaben entsteht.' },
      { _uid: 'fp-li-3', component: 'service_list_item', text: 'Ihr sucht ausschliesslich kurzfristige Zusatzkapazität für bereits vollständig spezifizierte Entwicklungstickets.' },
    ],
    alt_text: 'Wenn Nutzen, Priorität oder Richtung noch offen sind, beginnt ihr besser mit Klarheit. Wenn nur eine zentrale Annahme geprüft werden soll, ist Rapid Build wahrscheinlich der passendere Start.',
  },
  {
    _uid: 'fp-related',
    component: 'service_related',
    items: [
      { _uid: 'fp-rel-1', component: 'service_related_card', label: 'Klarheit', text: 'Wenn zuerst Wirkung, Priorität oder Richtung geklärt werden müssen.', href: '/services/klarheit' },
      { _uid: 'fp-rel-2', component: 'service_related_card', label: 'Rapid Build', text: 'Wenn ein begrenzter Produktausschnitt sichtbar getestet werden soll.', href: '/services/rapid-build' },
      { _uid: 'fp-rel-3', component: 'service_related_card', label: 'Urteil', text: 'Wenn ein bestehendes Produkt oder Konzept unabhängig eingeordnet werden soll.', href: '/services/urteil' },
    ],
  },
  {
    _uid: 'fp-cta',
    component: 'service_detail_cta',
    eyebrow: 'Nächster Schritt',
    headline: 'Lasst uns den ersten echten Alltag mitdenken.',
    body: 'In einem ersten Gespräch klären wir, was ein tragfähiger Start für euer Produkt wirklich braucht.',
    button_label: 'Gespräch starten →',
    button_url: '/contact',
  },
];
