// CMS-SERVICES-01: Statischer Fallback für /services Übersicht
// Wird verwendet wenn Storyblok nicht erreichbar oder Body ungültig.

export const FALLBACK_SERVICES_BODY = [
  {
    _uid: 'fs-hero',
    component: 'services_hero',
    eyebrow: 'Leistungen',
    headline: 'Nicht jede gute Idee braucht denselben Anfang.',
    body: 'Ob Nutzer etwas verstehen, eine Entscheidung treffen oder konkret handeln sollen: Das Erlebnis dahinter macht den Unterschied. Manche Vorhaben brauchen zuerst eine Entscheidung. Manche einen sichtbaren Beweis. Manche ein Produkt, das im Alltag trägt. Und manchmal braucht es eine ehrliche zweite Sicht, bevor etwas weiterläuft.',
  },
  {
    _uid: 'fs-cards',
    component: 'services_card_grid',
    eyebrow: 'Vier Einstiege',
    headline: 'Wo steht ihr gerade?',
    intro: 'Die Frage ist nicht, welche Leistung am besten klingt. Die Frage ist, an welchem Moment euer Vorhaben gerade feststeckt.',
    cards: [
      {
        _uid: 'fs-card-klarheit',
        component: 'service_card_item',
        label: '01 · Klarheit',
        title: 'Der Tisch ist voll. Die Entscheidung fehlt.',
        text: 'Es gibt Ideen, Erwartungen und mögliche Richtungen. Alles klingt plausibel. Genau deshalb wird nichts entschieden.',
        micro: 'Klarheit macht sichtbar, welche Frage jetzt wirklich beantwortet werden muss.',
        cta_label: 'Die offene Entscheidung sortieren →',
        href: '/services/klarheit',
        visual_type: 'klarheit',
      },
      {
        _uid: 'fs-card-rapid-build',
        component: 'service_card_item',
        label: '02 · Rapid Build',
        title: 'Die Idee ist da. Aber noch niemand hat sie erlebt.',
        text: 'Solange eine Idee nur beschrieben wird, stellt sich jede Person etwas anderes darunter vor. Erst ein konkreter Moment schafft eine gemeinsame Grundlage.',
        micro: 'Rapid Build macht die entscheidende Annahme sichtbar und testbar.',
        cta_label: 'Die Idee erlebbar machen →',
        href: '/services/rapid-build',
        visual_type: 'rapid-build',
      },
      {
        _uid: 'fs-card-produkt',
        component: 'service_card_item',
        label: '03 · Produkt',
        title: 'Die Richtung steht. Jetzt beginnt der erste echte Alltag.',
        text: 'Ein Produkt wird nicht durch ein Release tragfähig. Es wird tragfähig, wenn Menschen es verstehen, Systeme es mittragen und die nächste Entwicklung nicht wieder bei null beginnt.',
        micro: 'Produkt verbindet Erlebnis, Logik, Systeme und Weiterentwicklung.',
        cta_label: 'Den Produktmoment weiterdenken →',
        href: '/services/produkt',
        visual_type: 'produkt',
      },
      {
        _uid: 'fs-card-urteil',
        component: 'service_card_item',
        label: '04 · Urteil',
        title: 'Viel Arbeit ist schon da. Jetzt braucht es eine ungeschönte Sicht.',
        text: 'Ein Konzept, Angebot oder Produkt liegt vor. Gerade weil schon viel investiert wurde, braucht es einen ruhigen Blick darauf, was wirklich trägt.',
        micro: 'Urteil schafft Klarheit über Tragfähigkeit, offene Fragen und Konsequenzen.',
        cta_label: 'Die Prüfungsfrage klären →',
        href: '/services/urteil',
        visual_type: 'urteil',
      },
    ],
  },
  {
    _uid: 'fs-kai',
    component: 'kai_dialogue',
    eyebrow: 'Ein Gespräch beginnen',
    headline: 'Erzählt Kai, an welchem Moment ihr gerade steht.',
    intro: 'Ihr müsst eure Situation nicht zuerst in Leistungsnamen übersetzen. Beschreibt kurz, was bei euch gerade nicht weitergeht. Kai hilft euch, die Frage dahinter sichtbar zu machen.',
    context_key: 'services-story',
    initial_message: 'Hallo, ich bin Kai. Erzählt mir kurz, an welchem Punkt euer Vorhaben gerade feststeckt. Ich helfe euch, die eigentliche Frage zu sortieren.',
    input_placeholder: 'Was ist bei euch gerade der Moment, an dem es nicht weitergeht?',
    suggested_prompts: [
      'Wir haben zu viele mögliche Richtungen und kommen nicht zu einer Entscheidung.',
      'Wir glauben an eine Idee, können sie aber noch nicht zeigen.',
      'Unser Produkt funktioniert grundsätzlich, aber im Alltag wird es immer komplizierter.',
    ],
    privacy_notice: 'Bitte keine vertraulichen Projekt-, Kunden- oder Personendaten eingeben. Kai ist ein KI-Assistent von kenalu.',
    show_contact_cta: true,
  },
  {
    _uid: 'fs-approach',
    component: 'services_approach',
    eyebrow: 'Was alle vier Einstiege verbindet',
    headline: 'Die richtige Frage bleibt nah an der Umsetzung.',
    body: 'Kenalu verbindet strategische Klarheit, Experience Design und Engineering. Damit wichtige Annahmen nicht zwischen Konzept, Übergabe und Umsetzung verloren gehen.',
    link_label: 'So arbeitet Kenalu →',
    link_url: '/about',
  },
  {
    _uid: 'fs-cta',
    component: 'services_cta',
    eyebrow: 'Nächster Schritt',
    headline: 'Lieber mit einem Menschen sortieren?',
    body: 'In einem ersten Gespräch klären wir eure Ausgangslage, offene Fragen und den nächsten sinnvollen Schritt.',
    button_label: 'Gespräch starten →',
    button_url: '/contact',
  },
];
