// CMS-SERVICES-01: Statischer Fallback für /services/klarheit
export const FALLBACK_KLARHEIT_BODY = [
  {
    _uid: 'fk-hero',
    component: 'service_hero',
    sequence_label: '01 / Klarheit',
    headline: 'Viele Optionen. Keine Entscheidung.',
    intro: 'Neue AI-Ideen, Wünsche aus dem Business, ein digitales Angebot, das besser werden sollte, und vielleicht auch Druck, endlich etwas zu tun. Jede Richtung klingt plausibel. Genau deshalb fällt keine Entscheidung.',
    meta: 'Ein konzentrierter Entscheidungsraum · häufig 4–8 Arbeitstage',
    cta_label: 'Die offene Entscheidung besprechen →',
    cta_url: '/contact',
    hero_variant: '',
    h1_wide: false,
  },
  {
    _uid: 'fk-scene',
    component: 'service_scene',
    eyebrow: 'Der Moment davor',
    headline: 'Der Tisch wird voller. Die Richtung nicht klarer.',
    text_1: 'Im Lauf der Zeit kommen immer neue Gedanken dazu. Vertrieb sieht Chancen. Das Produktteam sieht Lücken. IT sieht Abhängigkeiten. Die Führung erwartet Bewegung. Jede Perspektive ist relevant – aber keine beantwortet allein die entscheidende Frage.',
    text_2: 'Klarheit beginnt deshalb nicht mit einer weiteren Idee. Sie beginnt damit, sichtbar zu machen, welche Entscheidung gerade wirklich offen ist.',
  },
  {
    _uid: 'fk-artifact',
    component: 'service_artifact',
    eyebrow: 'Was daraus entsteht',
    headline: 'Nicht alles wird klar. Aber das Entscheidende wird entscheidbar.',
    lead: 'Eine Entscheidungskarte verdichtet die Ausgangslage so, dass eine nächste Entscheidung nicht länger vertagt werden muss.',
    artifact_type: 'decision_map',
    items: [
      { _uid: 'fk-art-1', component: 'service_artifact_item', title: 'Was liegt auf dem Tisch?', text: 'Die Themen, Möglichkeiten und Erwartungen, die gerade gleichzeitig um Aufmerksamkeit konkurrieren.' },
      { _uid: 'fk-art-2', component: 'service_artifact_item', title: 'Welche Frage zählt?', text: 'Die eine Entscheidung, ohne die das Vorhaben nicht sinnvoll weiterkommt.' },
      { _uid: 'fk-art-3', component: 'service_artifact_item', title: 'Was spricht dafür?', text: 'Nutzen, Voraussetzungen, Risiken und Abhängigkeiten, die für diese Entscheidung relevant sind.' },
      { _uid: 'fk-art-4', component: 'service_artifact_item', title: 'Was folgt daraus?', text: 'Eine begründete Richtung und der nächste Schritt, der jetzt sinnvoll ist.' },
    ],
    note: 'Die Entscheidungskarte ist eine Arbeitsform von kenalu. Sie ist kein Kundenbeispiel.',
  },
  {
    _uid: 'fk-kai',
    component: 'kai_dialogue',
    eyebrow: 'Einmal laut denken',
    headline: 'Was liegt bei euch seit Wochen auf dem Tisch?',
    intro: 'Beschreibt Kai kurz, worüber ihr intern gerade diskutiert. Er hilft euch, die eigentliche Entscheidungsfrage herauszuarbeiten.',
    context_key: 'klarheit-story',
    initial_message: 'Hallo, ich bin Kai. Erzählt mir kurz, welche Entscheidung bei euch offen ist und warum sie bisher noch nicht gefallen ist.',
    input_placeholder: 'Welche Entscheidung wird bei euch gerade vertagt?',
    suggested_prompts: [
      'Wir sehen viele Möglichkeiten für AI, aber keine klare Priorität.',
      'Wir wollen ein digitales Angebot verbessern, wissen aber nicht, wo der Hebel liegt.',
      'Wir haben mehrere gute Ideen und können sie nicht sinnvoll vergleichen.',
    ],
    privacy_notice: 'Bitte keine vertraulichen Projekt-, Kunden- oder Personendaten eingeben. Kai ist ein KI-Assistent von kenalu.',
    show_contact_cta: true,
  },
  {
    _uid: 'fk-outcome',
    component: 'service_outcome',
    eyebrow: 'Danach',
    headline: 'Aus Diskussion wird ein nächster Schritt.',
    variant: '',
    items: [
      { _uid: 'fk-out-1', component: 'service_outcome_item', title: 'Prioritäten werden begründbar.', text: 'Nicht alles muss gleichzeitig passieren. Aber es wird klar, worauf sich Aufmerksamkeit und Investition zuerst richten sollten.' },
      { _uid: 'fk-out-2', component: 'service_outcome_item', title: 'Risiken werden früh sichtbar.', text: 'Offene Annahmen, fehlende Voraussetzungen und mögliche Sackgassen liegen auf dem Tisch, bevor sie teuer werden.' },
      { _uid: 'fk-out-3', component: 'service_outcome_item', title: 'Der nächste Schritt wird kleiner und klarer.', text: 'Vielleicht folgt ein Rapid Build. Vielleicht ein Produktvorhaben. Vielleicht bewusst noch nichts. Entscheidend ist, dass diese Wahl begründet ist.' },
    ],
  },
  {
    _uid: 'fk-honest',
    component: 'service_honest_fit',
    eyebrow: 'Ehrliche Einordnung',
    headline: 'Klarheit ist nicht immer der richtige Beginn.',
    list_items: [
      { _uid: 'fk-li-1', component: 'service_list_item', text: 'Ihr habt bereits eine bestätigte Richtung und müsst vor allem einen konkreten Produktausschnitt bauen.' },
      { _uid: 'fk-li-2', component: 'service_list_item', text: 'Ihr wollt ausschliesslich zusätzliche Entwicklungskapazität für ein klar definiertes Backlog.' },
      { _uid: 'fk-li-3', component: 'service_list_item', text: 'Ihr sucht eine allgemeine Inspirationssession ohne konkrete Entscheidung.' },
    ],
    alt_text: 'Wenn ihr bereits wisst, was sichtbar getestet werden soll, passt Rapid Build wahrscheinlich besser. Wenn ein Produktvorhaben klar genug umrissen ist, ist Produkt der passendere nächste Raum.',
  },
  {
    _uid: 'fk-related',
    component: 'service_related',
    items: [
      { _uid: 'fk-rel-1', component: 'service_related_card', label: 'Rapid Build', text: 'Wenn eine Annahme sichtbar getestet werden soll.', href: '/services/rapid-build' },
      { _uid: 'fk-rel-2', component: 'service_related_card', label: 'Produkt', text: 'Wenn eine bestätigte Richtung in ein tragfähiges Produkt überführt werden soll.', href: '/services/produkt' },
      { _uid: 'fk-rel-3', component: 'service_related_card', label: 'Urteil', text: 'Wenn ein bestehendes Vorhaben unabhängig eingeordnet werden soll.', href: '/services/urteil' },
    ],
  },
  {
    _uid: 'fk-cta',
    component: 'service_detail_cta',
    eyebrow: 'Nächster Schritt',
    headline: 'Lasst uns die offene Entscheidung sortieren.',
    body: 'In einem ersten Gespräch klären wir, welche Frage gerade wirklich beantwortet werden muss.',
    button_label: 'Gespräch starten →',
    button_url: '/contact',
  },
];
