// CMS-SERVICES-01: Statischer Fallback für /services/rapid-build
export const FALLBACK_RAPID_BUILD_BODY = [
  {
    _uid: 'frb-hero',
    component: 'service_hero',
    sequence_label: '02 / Rapid Build',
    headline: 'Eine Idee verändert sich, sobald jemand sie benutzen kann.',
    intro: 'Solange eine Idee nur beschrieben wird, stellt sich jede Person etwas anderes darunter vor. Im Meeting nicken alle. Im nächsten Gespräch beginnt die Diskussion von vorn. Rapid Build schafft den einen Moment, an dem eine Annahme nicht mehr erklärt werden muss, weil man sie erleben kann.',
    meta: 'Ein fokussierter Build · oft rund zwei Wochen',
    cta_label: 'Die entscheidende Annahme besprechen →',
    cta_url: '/contact',
    hero_variant: 'dynamic',
    h1_wide: false,
  },
  {
    _uid: 'frb-scene',
    component: 'service_scene',
    eyebrow: 'Der Moment davor',
    headline: 'Im Meeting nicken alle. Aber niemand sieht dasselbe.',
    text_1: 'Eine Idee kann in einer Präsentation plausibel wirken und trotzdem noch zu offen sein. Was passiert wirklich? Versteht jemand den Ablauf? Entsteht Nutzen? Würde jemand ihn wieder nutzen? Solange das nur beschrieben wird, bleiben Antworten Vermutungen.',
    text_2: 'Rapid Build baut nicht möglichst viel Produkt. Es baut gerade genug, damit eine zentrale Frage für Menschen sichtbar wird.',
  },
  {
    _uid: 'frb-artifact',
    component: 'service_artifact',
    eyebrow: 'Was daraus entsteht',
    headline: 'Ein kleiner Moment, der eine grosse Frage beantwortet.',
    lead: 'Nicht ein möglichst grosses MVP. Sondern ein begrenzter Produktausschnitt, der eine zentrale Annahme erlebbar und überprüfbar macht.',
    artifact_type: 'sequence',
    items: [
      { _uid: 'frb-art-1', component: 'service_artifact_item', item_id: '01', title: 'Die Annahme', text: 'Was muss wahr sein, damit sich dieser Build lohnt?' },
      { _uid: 'frb-art-2', component: 'service_artifact_item', item_id: '02', title: 'Der Moment', text: 'Welche Interaktion, welcher Service-Ablauf oder welche Entscheidung muss jemand erleben, damit diese Annahme sichtbar wird?' },
      { _uid: 'frb-art-3', component: 'service_artifact_item', item_id: '03', title: 'Die Reaktion', text: 'Was verstehen, erwarten, übersehen oder brauchen Menschen tatsächlich?' },
    ],
    note: 'Die Darstellung beschreibt eine Arbeitsform von kenalu und kein Kundenprodukt.',
  },
  {
    _uid: 'frb-outcome',
    component: 'service_outcome',
    eyebrow: 'Danach',
    headline: 'Aus Meinungen wird beobachtbares Feedback.',
    variant: 'highlighted',
    items: [
      { _uid: 'frb-out-1', component: 'service_outcome_item', title: 'Was funktioniert', text: 'Welche Teile der Idee Menschen sofort verstehen, nutzen oder als hilfreich erleben.' },
      { _uid: 'frb-out-2', component: 'service_outcome_item', title: 'Was fehlt', text: 'Wo Erwartungen, Inhalt, Ablauf oder technische Realität noch nicht zusammenpassen.' },
      { _uid: 'frb-out-3', component: 'service_outcome_item', title: 'Was als Nächstes zählt', text: 'Ob die Idee weiterverfolgt, angepasst, vertieft oder bewusst gestoppt werden sollte.' },
    ],
  },
  {
    _uid: 'frb-kai',
    component: 'kai_dialogue',
    eyebrow: 'Den Gedanken greifbar machen',
    headline: 'Was müsste jemand erleben, damit ihr nicht mehr raten müsst?',
    intro: 'Beschreibt Kai kurz eure Idee oder Hypothese. Er hilft euch, die eine Annahme zu finden, die zuerst sichtbar gemacht werden sollte.',
    context_key: 'rapid-build-story',
    initial_message: 'Hallo, ich bin Kai. Erzählt mir kurz, welche Idee ihr nicht länger nur diskutieren, sondern erlebbar machen möchtet.',
    input_placeholder: 'Was soll jemand sehen oder erleben können?',
    suggested_prompts: [
      'Wir müssen intern zeigen, wie unsere Idee konkret funktionieren könnte.',
      'Wir möchten prüfen, ob Nutzer diese Idee wirklich verstehen oder brauchen.',
      'Wir wollen nicht weiter diskutieren, sondern eine zentrale Annahme testen.',
    ],
    privacy_notice: 'Bitte keine vertraulichen Projekt-, Kunden- oder Personendaten eingeben. Kai ist ein KI-Assistent von kenalu.',
    show_contact_cta: true,
  },
  {
    _uid: 'frb-honest',
    component: 'service_honest_fit',
    eyebrow: 'Ehrliche Einordnung',
    headline: 'Rapid Build ist nicht für jede offene Situation der beste Start.',
    list_items: [
      { _uid: 'frb-li-1', component: 'service_list_item', text: 'Die grundlegende Richtung und der erwartete Nutzen sind noch völlig offen.' },
      { _uid: 'frb-li-2', component: 'service_list_item', text: 'Ihr braucht primär eine langfristige Produkt- oder Plattformarchitektur.' },
      { _uid: 'frb-li-3', component: 'service_list_item', text: 'Ihr wollt nur eine schöne Oberfläche, ohne eine konkrete Annahme prüfen zu wollen.' },
    ],
    alt_text: 'Wenn die zentrale Frage noch nicht klar genug ist, beginnt ihr wahrscheinlich mit Klarheit. Wenn die Richtung bestätigt ist und ein vollständigerer Produktaufbau ansteht, passt Produkt besser.',
  },
  {
    _uid: 'frb-related',
    component: 'service_related',
    items: [
      { _uid: 'frb-rel-1', component: 'service_related_card', label: 'Klarheit', text: 'Wenn zuerst die entscheidende Richtung gefunden werden muss.', href: '/services/klarheit' },
      { _uid: 'frb-rel-2', component: 'service_related_card', label: 'Produkt', text: 'Wenn aus dem getesteten Moment eine tragfähige Grundlage werden soll.', href: '/services/produkt' },
      { _uid: 'frb-rel-3', component: 'service_related_card', label: 'Urteil', text: 'Wenn ein bestehender Ansatz oder erster Build unabhängig eingeordnet werden soll.', href: '/services/urteil' },
    ],
  },
  {
    _uid: 'frb-cta',
    component: 'service_detail_cta',
    eyebrow: 'Nächster Schritt',
    headline: 'Lasst uns die entscheidende Annahme sichtbar machen.',
    body: 'In einem ersten Gespräch klären wir, was ein Build wirklich zeigen muss – und was noch nicht.',
    button_label: 'Gespräch starten →',
    button_url: '/contact',
  },
];
