// CMS-SERVICES-01: Statischer Fallback für /services/urteil
export const FALLBACK_URTEIL_BODY = [
  {
    _uid: 'fu-hero',
    component: 'service_hero',
    sequence_label: '04 / Urteil',
    headline: 'Manchmal braucht ein Vorhaben nicht mehr Energie. Sondern eine ungeschönte Sicht.',
    intro: 'Es gibt ein Konzept, ein Angebot, einen Prototypen oder ein laufendes Produkt. Viel Arbeit ist bereits hineingeflossen. Genau deshalb wird es schwierig, die entscheidende Frage noch offen zu stellen.',
    meta: 'Eine unabhängige Einordnung · meist 1–2 Wochen',
    cta_label: 'Die Prüfungsfrage besprechen →',
    cta_url: '/contact',
    hero_variant: 'editorial',
    h1_wide: false,
  },
  {
    _uid: 'fu-scene',
    component: 'service_scene',
    eyebrow: 'Der Moment davor',
    headline: 'Viel Arbeit ist bereits da. Die entscheidende Frage vielleicht noch nicht.',
    text_1: 'Unterlagen sehen überzeugend aus. Es gibt Argumente, Erwartungen und vielleicht auch schon erste Resultate. Aber je weiter ein Vorhaben voranschreitet, desto schwieriger wird es, ruhig zu fragen: Trägt das wirklich? Was fehlt? Welche Annahme wird gerade übersehen?',
    text_2: 'Urteil schafft Raum für genau diese Fragen. Nicht, um Arbeit kleinzureden. Sondern damit die nächste Entscheidung auf etwas Belastbarem steht.',
  },
  {
    _uid: 'fu-artifact',
    component: 'service_artifact',
    eyebrow: 'Was daraus entsteht',
    headline: 'Ein Urteil mit Konsequenz.',
    lead: 'Nicht eine lange Liste von Beobachtungen. Sondern eine verständliche Einordnung, die klar trennt, was trägt, was noch geklärt werden muss und was nicht weiterverfolgt werden sollte.',
    artifact_type: 'judgement',
    items: [
      { _uid: 'fu-art-1', component: 'service_artifact_item', variant: 'positive', title: 'Trägt', text: 'Was bereits nachvollziehbar, relevant und tragfähig ist.' },
      { _uid: 'fu-art-2', component: 'service_artifact_item', variant: 'open', title: 'Muss geklärt werden', text: 'Welche Annahmen, Risiken, Abhängigkeiten oder Lücken vor der nächsten Entscheidung noch offen sind.' },
      { _uid: 'fu-art-3', component: 'service_artifact_item', variant: 'stop', title: 'Sollte nicht weiterverfolgt werden', text: 'Welche Wege unverhältnismässig, unklar oder nicht sinnvoll sind.' },
      { _uid: 'fu-art-4', component: 'service_artifact_item', variant: 'conclusion', title: 'Nächste Konsequenz', text: 'Welche Entscheidung vorbereitet, verändert oder bewusst vertagt werden sollte.' },
    ],
    note: 'Das Urteil ist eine Arbeitsform von kenalu. Es ist keine juristische, regulatorische, finanzielle oder sicherheitstechnische Prüfung.',
  },
  {
    _uid: 'fu-kai',
    component: 'kai_dialogue',
    eyebrow: 'Die Prüfungsfrage finden',
    headline: 'Welche Entscheidung braucht bei euch eine zweite Sicht?',
    intro: 'Beschreibt Kai kurz, was bereits vorliegt. Er hilft euch, die wichtigste Prüfungsfrage zu formulieren.',
    context_key: 'urteil-story',
    initial_message: 'Hallo, ich bin Kai. Erzählt mir kurz, was ihr prüfen möchtet und welche Entscheidung davon abhängt.',
    input_placeholder: 'Was möchtet ihr unabhängig einordnen?',
    suggested_prompts: [
      'Wir haben ein Konzept und sind uns bei der Richtung nicht mehr sicher.',
      'Unser Vorhaben läuft, aber wir sehen Risiken, die wir nicht sauber einordnen können.',
      'Wir brauchen eine klare externe Sicht auf ein Angebot, Produkt oder einen geplanten nächsten Schritt.',
    ],
    privacy_notice: 'Bitte keine vertraulichen Projekt-, Kunden- oder Personendaten eingeben. Kai ist ein KI-Assistent von kenalu.',
    show_contact_cta: true,
  },
  {
    _uid: 'fu-outcome',
    component: 'service_outcome',
    eyebrow: 'Danach',
    headline: 'Aus einem Gefühl wird eine begründete Konsequenz.',
    variant: 'editorial',
    items: [
      { _uid: 'fu-out-1', component: 'service_outcome_item', title: 'Blinde Flecken werden sichtbar.', text: 'Nicht jede offene Frage ist ein Risiko. Aber es wird klarer, welche Fragen für die nächste Entscheidung wirklich zählen.' },
      { _uid: 'fu-out-2', component: 'service_outcome_item', title: 'Erwartungen werden sortiert.', text: 'Es wird sichtbar, was ein Konzept, Angebot oder Produkt leisten kann – und was nicht.' },
      { _uid: 'fu-out-3', component: 'service_outcome_item', title: 'Der nächste Schritt wird ehrlicher.', text: 'Weiterführen, verändern, vertiefen oder stoppen wird nicht emotionaler, sondern begründbarer.' },
    ],
  },
  {
    _uid: 'fu-honest',
    component: 'service_honest_fit',
    eyebrow: 'Ehrliche Einordnung',
    headline: 'Urteil ist nicht immer die sinnvollste erste Investition.',
    list_items: [
      { _uid: 'fu-li-1', component: 'service_list_item', text: 'Ihr habt noch keine Unterlagen, Richtung oder konkrete Fragestellung, die geprüft werden kann.' },
      { _uid: 'fu-li-2', component: 'service_list_item', text: 'Ihr möchtet vor allem eine neue Idee sichtbar und testbar machen.' },
      { _uid: 'fu-li-3', component: 'service_list_item', text: 'Ihr erwartet eine rechtliche, regulatorische, finanzielle oder sicherheitstechnische Zertifizierung.' },
    ],
    alt_text: 'Wenn zuerst eine Richtung entwickelt werden muss, beginnt ihr besser mit Klarheit. Wenn eine Idee sichtbar getestet werden soll, ist Rapid Build wahrscheinlich der sinnvollere Einstieg.',
  },
  {
    _uid: 'fu-related',
    component: 'service_related',
    items: [
      { _uid: 'fu-rel-1', component: 'service_related_card', label: 'Klarheit', text: 'Wenn zuerst eine begründete Richtung entstehen muss.', href: '/services/klarheit' },
      { _uid: 'fu-rel-2', component: 'service_related_card', label: 'Rapid Build', text: 'Wenn eine Idee oder Annahme sichtbar getestet werden soll.', href: '/services/rapid-build' },
      { _uid: 'fu-rel-3', component: 'service_related_card', label: 'Produkt', text: 'Wenn die Richtung steht und daraus ein tragfähiges Produkt werden soll.', href: '/services/produkt' },
    ],
  },
  {
    _uid: 'fu-cta',
    component: 'service_detail_cta',
    eyebrow: 'Nächster Schritt',
    headline: 'Lasst uns die Prüfungsfrage klar machen.',
    body: 'In einem ersten Gespräch klären wir, worauf euer Vorhaben wirklich geprüft werden sollte.',
    button_label: 'Gespräch starten →',
    button_url: '/contact',
  },
];
